Repository ITISFoundation/mmux_vite, pull requests merged in 2025-09, with the labels that each got.

#266 fix: changed output optimization configuration menu
  node/src/components/setup/OutputVariableDist.tsx
Labels: enhancement

#272 Fix missing /text-files directory in images
  .osparc/proxy-moga-read/runtime.yml
  .osparc/proxy-moga-write/runtime.yml
Labels: bug

#273 feat: added modal to insert values for samples, iterations and crossoverRate
  .bumpversion.cfg
  .osparc/flaskapi/metadata.yml
  .osparc/node/metadata.yml
  .osparc/proxy-moga-read/metadata.yml
  .osparc/proxy-moga-write/metadata.yml
  .osparc/proxy-sumo-read/metadata.yml
  .osparc/proxy-sumo-write/metadata.yml
  .osparc/proxy-uq-read/metadata.yml
  .osparc/proxy-uq-write/metadata.yml
  Makefile
  docker-compose-development.yml
  docker-compose-local.yml
  flaskapi/Dockerfile
  flaskapi/flask_workflows.py
  node/src/App.tsx
  node/src/components/data/JobSelector.tsx
  node/src/components/plots/MOGAPareto.tsx
  node/src/components/plots/MOGAParetoTable.tsx
  node/src/components/plots/UncertainUQ.tsx
  node/src/components/sampling/GridSearchSampling.tsx
  node/src/components/utils/OptionSelect.tsx
  node/src/context/MMUXContext.test.tsx
  node/src/context/MMUXContext.tsx
  node/src/context/MOGASettingsContext.test.tsx
  node/src/context/MOGASettingsContext.tsx
  node/src/context/MOGATableContext.test.tsx
  node/src/context/MOGATableContext.tsx
  node/src/context/PersistenceContext.tsx
  node/src/context/SamplingContext.tsx
  node/src/context/samplePersistence.test.json
  node/src/context/types.d.ts
  node/src/global.d.ts
  node/src/views/MOGA.tsx
  node/src/views/MOGAModal.tsx
  node/src/views/OutputSetup.tsx
Labels: enhancement

#283 fix: added color highlight min max to number fields
  node/src/components/utils/InputBlock.tsx
  node/src/views/MOGAModal.tsx
Labels: bug

#294 Fix variable sanitization minmax options
  flaskapi/data_preprocessor/FILTERING_FEATURES.md
  flaskapi/data_preprocessor/README_DataPreprocessor.md
  flaskapi/data_preprocessor/data_preprocessor.py
  flaskapi/data_preprocessor/data_preprocessor_integration.py
  flaskapi/data_preprocessor/data_preprocessor_testing.py
  flaskapi/data_preprocessor/test_variable_filtering.py
  flaskapi/flask_workflows.py
Labels: enhancement

#300 Avoid calling get_function_job many times after sampling
  node/src/components/sampling/LHSSampling.tsx
Labels: enhancement

#302 fix: now performance weights drag-bar properly update when outputs change
  node/src/components/plots/MOGAPareto.tsx
  node/src/components/plots/MOGAParetoTable.tsx
  node/src/components/plots/PerformanceModal.tsx
Labels: bug

#301 fix: now jobs are properly filtered and updated when checked
  node/src/components/plots/Surface2DPlot.tsx
  node/src/components/plots/UncertainUQ.tsx
  node/src/components/sampling/LHSSampling.tsx
  node/src/context/JobContext.tsx
Labels: bug

#303 fix: job status now does not change width, hover to see full text
  node/src/components/data/JobRow.tsx
  node/src/components/data/JobSelector.tsx
Labels: bug

#306 fix: used custom tooltip to show uid for jobcollections
  node/src/components/data/JobRow.tsx
  node/src/components/data/JobSelector.tsx
Labels: bug

#308 fix: now sampling points only update after leaving the value box
  node/src/components/data/JobRow.tsx
  node/src/components/sampling/LHSSampling.tsx
  node/src/utils/stepValidator.ts
Labels: bug

#317 fix: changed useEffects to properly update plot data
  node/src/components/plots/MOGAPareto.tsx
Labels: bug

#322 fix: modified the seed minimum value and handled error
  node/src/components/sampling/LHSSampling.tsx
Labels: bug

#325 289 enable selection of plotting variables in 1d2d3d moga plots
  node/src/components/plots/MOGAPareto.tsx
  node/src/components/plots/MOGAPlotModal.tsx
  node/src/components/plots/PlotTools.tsx
  node/src/views/MOGAModal.tsx
Labels: enhancement

#355 Increase number of gunicorn workers to 4
  flaskapi/entrypoint.sh
Labels: release

#357 Check projectjobid
  flaskapi/flask_workflows.py
Labels: flaskapi
